import os
import re
import numpy as np
from argparse import ArgumentParser

from flatland.envs.rail_env import RailEnv
from flatland.core.transition_map import GridTransitionMap
from flatland.envs.agent_utils import EnvAgent

# Custom modules based on your architecture
from modules.dirs import create_dirs
from modules.save import save_png, save_pkl

def parse_lp_to_env(lp_filepath):
    with open(lp_filepath, 'r') as f:
        content = f.read()

    # 1. Extract dimensions from the comment header generated by convert.py
    dim_match = re.search(r'% height: (\d+), width: (\d+)', content)
    if not dim_match:
        raise ValueError("Could not find height and width in the .lp file header.")
    height, width = int(dim_match.group(1)), int(dim_match.group(2))

    # 2. Reconstruct the rail grid
    grid = np.zeros((height, width), dtype=np.uint16)
    for y, x, val in re.findall(r'cell\(\((\d+),\s*(\d+)\),\s*(\d+)\)', content):
        grid[int(y), int(x)] = int(val)

    transition_map = GridTransitionMap(width, height)
    transition_map.grid = grid

    # 3. Initialize an empty environment and inject the parsed grid
# 3. Initialize an empty environment and inject the parsed grid
    env = RailEnv(width=width, height=height, number_of_agents=0)
    env.rail = transition_map
    env.height = height
    env.width = width
    
    # Parse and set the global max episode steps
    global_match = re.search(r'global\((\d+)\)\.', content)
    if global_match:
        env._max_episode_steps = int(global_match.group(1))

    # 4. Parse agent data (Updated to capture departure and arrival times)
    dir_map_inv = {"n": 0, "e": 1, "s": 2, "w": 3}
    
    starts = {int(id_): (int(y), int(x), dir_map_inv[d], int(dep)) for id_, y, x, dep, d in re.findall(r'start\((\d+),\s*\((\d+),\s*(\d+)\),\s*(\d+),\s*([nesw])\)', content)}
    ends = {int(id_): (int(y), int(x), int(arr)) for id_, y, x, arr in re.findall(r'end\((\d+),\s*\((\d+),\s*(\d+)\),\s*(\d+)\)', content)}
    speeds = {int(id_): int(s) for id_, s in re.findall(r'speed\((\d+),\s*(\d+)\)', content)}

    # 5. Reconstruct agents (Updated to set time constraints)
    env.agents = []
    for agent_id in sorted(starts.keys()):
        start_y, start_x, direction, earliest_dep = starts[agent_id]
        target_y, target_x, latest_arr = ends[agent_id]
        speed_inv = speeds.get(agent_id, 1)
        
        agent = EnvAgent(
            initial_position=(start_y, start_x),
            initial_direction=direction,
            direction=direction,
            target=(target_y, target_x),
            moving=False
        )
        agent.position = (start_y, start_x) # You can change this back to None later if you want them off-map visually
        agent.speed_counter._speed = 1.0 / speed_inv
        
        # Inject the parsed time parameters
        agent.earliest_departure = earliest_dep
        agent.latest_arrival = latest_arr
        
        env.agents.append(agent)

    return env

def main():
    parser = ArgumentParser(description="Generate a Flatland pkl and png from an existing Clingo lp file.")
    parser.add_argument('lp_file', type=str, help='Path to the .lp file')
    args = parser.parse_args()

    print(f"Parsing {args.lp_file}...")
    env = parse_lp_to_env(args.lp_file)

    # Setup directories and save
    path = create_dirs()
    base_name = os.path.splitext(os.path.basename(args.lp_file))[0]
    
    print(f"Saving .pkl and .png for {base_name}...")
    save_png(env, base_name, path)
    save_pkl(env, base_name, path)
    
    print("Environment successfully reconstructed and saved.")

if __name__ == "__main__":
    main()